# Generated by Django 2.0.2 on 2018-03-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favourite',
            new_name='favourite',
        ),
    ]
