# Generated by Django 2.0.2 on 2018-03-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180331_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='favourite',
            new_name='is_favourite',
        ),
    ]
