# Generated by Django 2.0 on 2018-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180505_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(error_messages={'unique': 'Audio file must be  MP3'}, upload_to=''),
        ),
    ]
