# Generated by Django 2.0 on 2018-05-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180505_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(error_messages={'unique': 'Audio file must be  MP3'}, max_length=250),
        ),
    ]
